# Generated by Django 5.0.3 on 2024-03-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("duplicati", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="run",
            unique_together={("job", "begin")},
        ),
    ]
